name: Publish docker image
on:
  release:
    types: [published]
jobs:
  main:
    name: Build and push docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - amxx_version: "1.8.2"
            base_url: "https://www.amxmodx.org/release/amxmodx-1.8.2-base-linux.tar.gz"
          - amxx_version: "1.8.3-git5201"
            base_url: "https://www.amxmodx.org/amxxdrop/1.8/amxmodx-1.8.3-dev-git5201-base-linux.tar.gz"
          - amxx_version: "1.9.0-git5241"
            base_url: "https://www.amxmodx.org/amxxdrop/1.9/amxmodx-1.9.0-git5241-base-linux.tar.gz"
          - amxx_version: "1.10.0-git5392"
            base_url: "https://www.amxmodx.org/amxxdrop/1.10/amxmodx-1.10.0-git5392-base-linux.tar.gz"
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: budziam/amxx-builder:${{ matrix.amxx_version }}
          build-args: |
            BASE_URL=${{ matrix.base_url }}
